// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bank/type/account.proto

package bank

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	date "google.golang.org/genproto/googleapis/type/date"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrentBalanceRequest struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentBalanceRequest) Reset()         { *m = CurrentBalanceRequest{} }
func (m *CurrentBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*CurrentBalanceRequest) ProtoMessage()    {}
func (*CurrentBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06fc771b79c6e49a, []int{0}
}

func (m *CurrentBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentBalanceRequest.Unmarshal(m, b)
}
func (m *CurrentBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentBalanceRequest.Marshal(b, m, deterministic)
}
func (m *CurrentBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentBalanceRequest.Merge(m, src)
}
func (m *CurrentBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_CurrentBalanceRequest.Size(m)
}
func (m *CurrentBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentBalanceRequest proto.InternalMessageInfo

func (m *CurrentBalanceRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type CurrentBalanceResponse struct {
	Amount               float64    `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrentDate          *date.Date `protobuf:"bytes,2,opt,name=current_date,proto3" json:"current_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CurrentBalanceResponse) Reset()         { *m = CurrentBalanceResponse{} }
func (m *CurrentBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentBalanceResponse) ProtoMessage()    {}
func (*CurrentBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06fc771b79c6e49a, []int{1}
}

func (m *CurrentBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentBalanceResponse.Unmarshal(m, b)
}
func (m *CurrentBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentBalanceResponse.Marshal(b, m, deterministic)
}
func (m *CurrentBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentBalanceResponse.Merge(m, src)
}
func (m *CurrentBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentBalanceResponse.Size(m)
}
func (m *CurrentBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentBalanceResponse proto.InternalMessageInfo

func (m *CurrentBalanceResponse) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CurrentBalanceResponse) GetCurrentDate() *date.Date {
	if m != nil {
		return m.CurrentDate
	}
	return nil
}

type CreateAccountRequest struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=account_name,proto3" json:"account_name,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	InitialDepositAmount float64  `protobuf:"fixed64,3,opt,name=initial_deposit_amount,proto3" json:"initial_deposit_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06fc771b79c6e49a, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *CreateAccountRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CreateAccountRequest) GetInitialDepositAmount() float64 {
	if m != nil {
		return m.InitialDepositAmount
	}
	return 0
}

type CreateAccountResponse struct {
	AccountUuid          string   `protobuf:"bytes,1,opt,name=account_uuid,proto3" json:"account_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06fc771b79c6e49a, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccountUuid() string {
	if m != nil {
		return m.AccountUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrentBalanceRequest)(nil), "bank.CurrentBalanceRequest")
	proto.RegisterType((*CurrentBalanceResponse)(nil), "bank.CurrentBalanceResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "bank.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "bank.CreateAccountResponse")
}

func init() {
	proto.RegisterFile("proto/bank/type/account.proto", fileDescriptor_06fc771b79c6e49a)
}

var fileDescriptor_06fc771b79c6e49a = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0x4a, 0xb1, 0x6b, 0x11, 0x0c, 0xb6, 0x94, 0xa2, 0x50, 0x72, 0x90, 0x5e, 0x9a,
	0x80, 0x7f, 0x7a, 0xf1, 0x20, 0xb6, 0x3e, 0x41, 0x8e, 0x5e, 0xc2, 0x64, 0x3b, 0x6c, 0x97, 0x76,
	0x77, 0xe3, 0x66, 0xf6, 0x90, 0x97, 0xf0, 0x99, 0x25, 0xbb, 0xb1, 0xd8, 0x80, 0x97, 0x85, 0xf9,
	0xe6, 0x9b, 0x6f, 0x7f, 0xc3, 0xb0, 0xfb, 0xca, 0x1a, 0x32, 0x59, 0x09, 0x7a, 0x9f, 0x51, 0x53,
	0x61, 0x06, 0x9c, 0x1b, 0xa7, 0x29, 0xf5, 0x7a, 0x7c, 0xd1, 0x36, 0x66, 0x77, 0xc1, 0x24, 0x8c,
	0x11, 0x07, 0x0c, 0xb6, 0x2d, 0x10, 0x06, 0x4f, 0xf2, 0xc6, 0xc6, 0x1b, 0x67, 0x2d, 0x6a, 0x5a,
	0xc3, 0x01, 0x34, 0xc7, 0x1c, 0xbf, 0x1c, 0xd6, 0x14, 0x3f, 0xb0, 0xeb, 0x2e, 0xad, 0xd0, 0x4e,
	0x95, 0x68, 0xa7, 0xd1, 0x3c, 0x5a, 0x0c, 0xf3, 0x9e, 0x9a, 0x08, 0x36, 0xe9, 0x07, 0xd4, 0x95,
	0xd1, 0x35, 0xc6, 0x13, 0x36, 0x00, 0xd5, 0x5a, 0xfd, 0x64, 0x94, 0x77, 0x55, 0xfc, 0xc2, 0x46,
	0x3c, 0x4c, 0x14, 0x2d, 0xc8, 0xf4, 0x6c, 0x1e, 0x2d, 0xae, 0x1e, 0x6f, 0xd2, 0x40, 0x98, 0xb6,
	0x84, 0xe9, 0x07, 0x10, 0xe6, 0x27, 0xb6, 0xe4, 0x3b, 0x62, 0xb7, 0x1b, 0x8b, 0x40, 0xf8, 0x1e,
	0x08, 0x7e, 0x49, 0x13, 0x36, 0x3a, 0x32, 0x81, 0xc2, 0x8e, 0xf3, 0x44, 0x8b, 0x67, 0xec, 0x32,
	0x84, 0xf1, 0xc6, 0xff, 0x37, 0xcc, 0x8f, 0x75, 0xbc, 0x62, 0x13, 0xa9, 0x25, 0x49, 0x38, 0x14,
	0x5b, 0xac, 0x4c, 0x2d, 0xa9, 0xe8, 0xb8, 0xcf, 0x3d, 0xf7, 0x3f, 0xdd, 0xe4, 0x95, 0x8d, 0x7b,
	0x3c, 0xdd, 0xe2, 0x7f, 0x80, 0x9c, 0x93, 0xdb, 0x3e, 0x50, 0xab, 0xad, 0x57, 0x9f, 0xcf, 0x42,
	0xd2, 0xce, 0x95, 0x29, 0x37, 0x2a, 0x23, 0x54, 0xb8, 0x87, 0x5d, 0x0d, 0x4d, 0xa6, 0x9a, 0xa5,
	0xb0, 0x15, 0x5f, 0x86, 0xab, 0xf9, 0x57, 0xa0, 0xce, 0x44, 0x38, 0x73, 0x39, 0xf0, 0xca, 0xd3,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0xb1, 0x15, 0xfe, 0xfb, 0x01, 0x00, 0x00,
}
