// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hello/hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32   `protobuf:"varint,16,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43bcc4e100789d78, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type HelloResponse struct {
	Greet                string   `protobuf:"bytes,1,opt,name=greet,proto3" json:"greet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43bcc4e100789d78, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreet() string {
	if m != nil {
		return m.Greet
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "hello.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "hello.HelloResponse")
}

func init() {
	proto.RegisterFile("proto/hello/hello.proto", fileDescriptor_43bcc4e100789d78)
}

var fileDescriptor_43bcc4e100789d78 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x5d, 0xb5, 0xa2, 0x83, 0x85, 0x32, 0x16, 0x2c, 0x9e, 0x4a, 0x40, 0xc8, 0xa5, 0x49,
	0xf1, 0x0f, 0xbd, 0x79, 0xb0, 0x14, 0xbc, 0x78, 0x49, 0x3c, 0x79, 0xdb, 0x86, 0x61, 0x13, 0x6c,
	0x76, 0xe3, 0xee, 0xa6, 0xb0, 0x9f, 0xc3, 0x2f, 0x2c, 0xdd, 0x5d, 0x51, 0x8f, 0xb9, 0x0c, 0x6f,
	0x1e, 0xbc, 0xdf, 0x0c, 0x3c, 0xb8, 0xee, 0xb4, 0xb2, 0x2a, 0xaf, 0x69, 0xb7, 0x8b, 0x33, 0xf3,
	0x0e, 0x8e, 0xfc, 0x92, 0x3c, 0xc0, 0xe5, 0xcb, 0x41, 0x14, 0xf4, 0xd9, 0x93, 0xb1, 0x88, 0x70,
	0x2a, 0x79, 0x4b, 0x33, 0x36, 0x67, 0xe9, 0x45, 0xe1, 0x35, 0x4e, 0xe0, 0x84, 0x0b, 0x9a, 0x4d,
	0xe6, 0x2c, 0x1d, 0x17, 0x07, 0x99, 0xdc, 0xc2, 0x38, 0xa6, 0x4c, 0xa7, 0xa4, 0x21, 0x9c, 0xc2,
	0x48, 0x68, 0x22, 0x1b, 0x73, 0x61, 0xb9, 0xfb, 0x3a, 0x8e, 0xf4, 0x92, 0xf4, 0xbe, 0xa9, 0x08,
	0x57, 0x70, 0x5e, 0x72, 0xe7, 0x2d, 0xbc, 0xca, 0xc2, 0x3b, 0x7f, 0xcf, 0xdf, 0x4c, 0xff, 0x9b,
	0x81, 0x9e, 0x1c, 0xe1, 0x13, 0x8c, 0x4b, 0xee, 0x5e, 0xb9, 0x0c, 0x61, 0x33, 0x28, 0xbd, 0x64,
	0xb8, 0x06, 0xfc, 0x39, 0xfc, 0xa6, 0x36, 0x7b, 0xd2, 0x4e, 0x49, 0x1a, 0x04, 0x49, 0x19, 0x6e,
	0x7e, 0x21, 0x6b, 0x25, 0x6d, 0x23, 0x7b, 0xd5, 0x9b, 0x81, 0x90, 0x25, 0x7b, 0x5e, 0xbd, 0x3f,
	0x8a, 0xc6, 0xd6, 0xfd, 0x36, 0xab, 0x54, 0x9b, 0x5b, 0x6a, 0xe9, 0x83, 0xd7, 0x86, 0xbb, 0xbc,
	0x75, 0x0b, 0xa1, 0xbb, 0x6a, 0x11, 0x2a, 0xf3, 0x53, 0x90, 0xcc, 0x45, 0x2c, 0x6e, 0x7b, 0xe6,
	0xad, 0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x3b, 0xe7, 0x3b, 0xd4, 0x01, 0x00, 0x00,
}
